import React, { useContext, useEffect } from 'react'
import { ProjectContext } from '../contexts/ProjectContext'
import { useParams } from 'react-router-dom'
import SectionHeader from '../components/elements/SectionHeader'
import { Link } from 'react-router-dom'

const Project = () => {
    const { id } = useParams()
    const {project, getProject} = useContext(ProjectContext)

    useEffect(() => {
        getProject(id)
    }, [id])

    if (!project || !project.id) {
      return <p>Loading project details...</p>
  }

  return (
    <main id='project'>
        <div className='container'>
            <SectionHeader title={`PROJECT ${project.id} - ${project.projectName}`} />

            {/* Generated by ChatGTP */}
            <div className="project-details">
                    <p><strong>Description:</strong> {project.description || "No description available"}</p>
                    <p><strong>Start Date:</strong> {new Date(project.startDate).toLocaleDateString()}</p>
                    <p><strong>End Date:</strong> {project.endDate ? new Date(project.endDate).toLocaleDateString() : "Ongoing"}</p>
                    <p><strong>Status:</strong> {project.status?.statusName || "Unknown"}</p>
                    <p><strong>Customer:</strong> {project.customer?.customerName || "No customer assigned"}</p>
                    <p><strong>Project Manager:</strong> {project.projectManager?.employee?.displayName || "No manager assigned"}</p>
                    <p><strong>Service:</strong> {project.service?.serviceName || "No service specified"}</p>
                    <p><strong>Project Type:</strong> {project.projectType?.typeName || "No type specified"}</p>
                </div>

            <Link to='/projects/update' className='btn btn-gray'>Update Project</Link>
        </div>
    </main>
  )
}

export default Project